[package]
name = "json_schema_store"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/json_schema_store.rs"

[features]
default = []

[dependencies]
anyhow.workspace = true
gpui.workspace = true
util.workspace = true
project.workspace = true
async-trait.workspace = true
settings.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true


# Uncomment other workspace dependencies as needed
# assistant.workspace = true
# client.workspace = true
# project.workspace = true
# settings.workspace = true
